version: 0.2

phases:
  pre_build:
    commands:
      - echo "Logging in to Amazon ECR..."
      - REPOSITORY_URI=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$ECR_REPO
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $REPOSITORY_URI
      - echo "Injecting GitHub token into requirements.txt"
      - sed -i "s|{GITHUB_TOKEN}|$GITHUB_TOKEN|g" requirements.txt

  build:
    commands:
      - echo "Build started on $(date)"
      - echo "Building the Docker image..."
      - IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - docker build -t $REPOSITORY_URI:latest .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG

  post_build:
    commands:
      - echo "Build completed on $(date)"
      - echo "Pushing the Docker images to ECR..."
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo "Updating Lambda function..."
      - aws lambda update-function-code --function-name $LAMBDA_FUNCTION --image-uri $REPOSITORY_URI:$IMAGE_TAG
      - echo "deployment completed"
